remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "WingEd/README.md"
    values:
      links:
        -
          title: GitHub
          url: https://github.com/vanjac/winged
  -
    scope:
      path: "WingEd/*.html"
    values:
      layout: default
      navigation: "/WingEd/navigation.html"
