# Configuration file for Iosevka
# See: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md
# Run: npm run build -- webfont-unhinted::IosevkaAileCustom

### Iosevka Aile ###

[buildPlans.IosevkaAileCustom]
family = "Iosevka Aile Custom"
spacing = "quasi-proportional"
noCvSs = true
noLigation = true
exportGlyphNames = false

variants.inherits = "buildPlans.IosevkaAile"
widths.inherits = "buildPlans.IosevkaAile"
derivingVariants.inherits = "buildPlans.IosevkaAile"

webfontFormats = ['WOFF2', 'TTF']

[buildPlans.IosevkaAileCustom.excludeChars]
# https://typeof.net/Iosevka/specimen
ranges = [
    # Include:         0000-00FF (Basic Latin, Latin 1 Supplement)
    [ 256, 787 ],    # 0100-0313
    # Include:         0314-0317 (partial Combining Diacritical Marks)
    [ 792, 8191 ],   # 0370-1FFF
    # Include:         2000-206F (General Punctuation)
    [ 8304, 8591 ],  # 2070-209F
    # Include:         2190-2195 (partial Arrows)
    [ 8598, 65278 ], # 2196-FEFE
    # Include:         FEFF-FFFF (ZWNBSP, Specials)
    [ 65536, 131071 ], # 10000-1FFFF
]

[buildPlans.IosevkaAileCustom.weights.Regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.IosevkaAileCustom.weights.Bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.IosevkaAileCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.IosevkaAileCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

### Iosevka Fixed ###

[buildPlans.IosevkaFixedCustom]
family = "Iosevka Fixed Custom"
spacing = "fixed"
noCvSs = true
noLigation = true
exportGlyphNames = false

webfontFormats = ['WOFF2', 'TTF']

[buildPlans.IosevkaFixedCustom.excludeChars]
ranges = [
    # Include:         0000-00FF (Basic Latin, Latin 1 Supplement)
    [ 256, 787 ],    # 0100-0313
    # Include:         0314-0317 (partial Combining Diacritical Marks)
    [ 792, 8191 ],   # 0370-1FFF
    # Include:         2000-206F (General Punctuation)
    [ 8304, 8591 ],  # 2070-209F
    # Include:         2190-2195 (partial Arrows)
    [ 8598, 65278 ], # 2196-FEFE
    # Include:         FEFF-FFFF (ZWNBSP, Specials)
    [ 65536, 131071 ], # 10000-1FFFF
]

[buildPlans.IosevkaFixedCustom.weights.Regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.IosevkaFixedCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.IosevkaFixedCustom.widths.Normal]
shape = 500
menu  = 5
css   = "normal"
